# Generated by Django 5.0.7 on 2024-07-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("rank", models.PositiveIntegerField()),
                ("director", models.CharField(max_length=50)),
                ("actor", models.CharField(max_length=100)),
                ("running_time", models.PositiveIntegerField()),
                ("content", models.TextField()),
            ],
        ),
    ]
