# Generated by Django 5.0.7 on 2024-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Adventure", "Adventure"),
                    ("Animation", "Animation"),
                    ("Comedy", "Comedy"),
                    ("Crime", "Crime"),
                    ("Documentary", "Documentary"),
                    ("Drama", "Drama"),
                    ("Family", "Family"),
                    ("Fantasy", "Fantasy"),
                    ("Horror", "Horror"),
                    ("Musical", "Musical"),
                    ("Romance", "Romance"),
                    ("SF", "SF"),
                    ("Sport", "Sport"),
                    ("Thriller", "Thriller"),
                ],
                max_length=50,
            ),
        ),
    ]
