# Generated by Django 5.0.7 on 2024-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_reviews_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews_images/"),
        ),
    ]
